# Generated by Django 5.1 on 2024-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallerymodel',
            name='dog_details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallerymodel',
            name='dog_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imagegallerymodel',
            name='dog_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallerymodel',
            name='dog_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
